# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run static analysis, unit/widget tests, and build IPA for PR checks"
  lane :validate_pr do
    flutter_root = File.expand_path("../..", __dir__)
    Dir.chdir(flutter_root) do
      sh("flutter pub get")
      sh("flutter test")
    end

    # Re-install CocoaPods to fix Ruby version mismatch on CI runners
    sh("gem install cocoapods --no-document")
    cocoapods(
      podfile: File.join(flutter_root, "ios"),
      try_repo_update_on_error: true
    )

    Dir.chdir(flutter_root) do
      sh("flutter build ios --no-codesign")
    end
  end
end
